export const services = [
    {
      id: 1,
      client_name: "Acme Corporation",
      work_location: "New York, NY",
      requested_by: "John Smith",
      scope: "Web Development",
      scope_description: "Develop and deploy a new e-commerce website",
      employee_details: "Jane Doe (Developer)",
      work_duration: "4 weeks",
      date: "2024-07-15",
      cost: "$10,000",
      invoice_code: "INV-0001"
    },
    {
      id: 2,
      client_name: "Brilliant Labs",
      work_location: "Seattle, WA",
      requested_by: "Jane Doe",
      scope: "Mobile App Development",
      scope_description: "Create a native iOS and Android app for data visualization",
      employee_details: "Sarah Miller (Project Manager)",
      work_duration: "6 weeks",
      date: "2024-07-10",
      cost: "$15,000",
      invoice_code: "INV-0002"
    },
    {
      id: 3,
      client_name: "Green Solutions",
      work_location: "Los Angeles, CA",
      requested_by: "Michael Brown",
      scope: "SEO Optimization",
      scope_description: "Improve website ranking for relevant keywords",
      employee_details: "Alice Young (SEO Specialist)",
      work_duration: "2 months",
      date: "2024-06-20",
      cost: "$8,000",
      invoice_code: "INV-0003"
    },
    {
      id: 4,
      client_name: "Technovation Inc.",
      work_location: "Remote",
      requested_by: "Sarah Jones",
      scope: "Cloud Migration",
      scope_description: "Migrate company infrastructure to a cloud platform",
      employee_details: "Robert Williams (Cloud Architect)",
      work_duration: "3 months",
      date: "2024-05-15",
      cost: "$20,000",
      invoice_code: "INV-0004"
    },
    {
      id: 5,
      client_name: "Fashion Boutique",
      work_location: "London, UK",
      requested_by: "David Lee",
      scope: "Graphic Design",
      scope_description: "Design new logo and branding materials",
      employee_details: "Amanda Johnson (Graphic Designer)",
      work_duration: "2 weeks",
      date: "2024-07-20",
      cost: "$5,000",
      invoice_code: "INV-0005"
    },
    {
      id: 6,
      client_name: "Happy Meals",
      work_location: "Chicago, IL",
      requested_by: "Emily Brown",
      scope: "Social Media Marketing",
      scope_description: "Develop and implement social media marketing campaigns",
      employee_details: "Matthew Miller (Social Media Manager)",
      work_duration: "1 month",
      date: "2024-07-01",
      cost: "$7,000",
      invoice_code: "INV-0006"
    },
    {
      id: 7,
      client_name: "Fitness Club",
      work_location: "Berlin, Germany",
      requested_by: "Charles Williams",
      scope: "Content Writing",
      scope_description: "Create blog posts and website content",
      employee_details: "Sophia Garcia (Editor)",
      work_duration: "Ongoing",
      date: "2024-06-01",
      cost: "$3,000",
      invoice_code: "INV-0007"
    },
    {
      id: 8,
      client_name: "Travel Agency",
      work_location: "Paris, France",
      requested_by: "Amanda Lee",
      scope: "Web Design",
      scope_description: "Redesign and develop a user-friendly travel booking website",
      employee_details: "Ashley Young (Web Designer)",
      work_duration: "8",
      date: "2024-06-04",
      cost: "$3,000",
      invoice_code: "INV-0008"
    }
  ]
  export const recentInvoicesRows = [
    { id: 1, name: 'Jon Snow', email: 'Jon@gmail.com', issueDate:'08-07-24',invoice:'8795646525451',dueDate:'08-09-24',payment:'300',balance:'550',dueAmount: 'Ksh.1400',status: 'Paid' },
    { id: 2, name: 'Cersei Lannister', email: 'Cersei@gmail.com', issueDate:'08-07-24',invoice:'8795646525451',dueDate:'08-09-24',payment:'300',balance:'550',dueAmount: 'Ksh.310',status: 'Paid' },
    { id: 3, name: 'Jaime Lannister', email: 'Jaime@gmail.com', issueDate:'08-07-24',invoice:'8795646525451',dueDate:'08-09-24',payment:'300',balance:'550',dueAmount: 'Ksh.2550',status:'Pending' },
    { id: 4, name: 'Arya Stark', email: 'Arya@gmail.com', issueDate:'08-07-24',invoice:'8795646525451',dueDate:'08-09-24',payment:'300',balance:'550',dueAmount: 'Ksh.110',status:'Cancelled' },
    { id: 5, name: 'Daenerys Targaryen', email: 'Daenerys@gmail.com', issueDate:'08-07-24',invoice:'8795646525451',dueDate:'08-09-24',payment:'300',balance:'550',dueAmount: 'Ksh.570',status:'Pending' },
    { id: 6, name: 'Jaime Lannister', email: 'Jaime@gmail.com', issueDate:'08-07-24',invoice:'8795646525451',dueDate:'08-09-24',payment:'300',balance:'550',dueAmount: 'Ksh.250',status:'Paid' },
    { id: 7, name: 'Arya Stark', email: 'Arya@gmail.com', issueDate:'08-07-24',invoice:'8795646525451',dueDate:'08-09-24',payment:'300',balance:'550',dueAmount: 'Ksh.110',status:'Cancelled' },
    { id: 8, name: 'Daenerys Targaryen', email: 'Daenerys@gmail.com', issueDate:'08-07-24',invoice:'8795646525451',dueDate:'08-09-24',payment:'300',balance:'550',dueAmount: 'Ksh.570',status: 'Pending'},
  ];